INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (5, 'Бази даних', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (6, 'Бази даних', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (7, 'Об''єктно орієнтоване програмування', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (8, 'Об''єктно орієнтоване програмування', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (9, 'Менеджмент', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (10, 'Економічна теорія', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (11, 'Економічна теорія', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (12, 'Менеджмент', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (13, 'Проектний практикум', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (14, 'Проектний практикум', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (15, 'Професійна практика', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (16, 'Професійна практика', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (17, 'Економіка програмного забезпечення', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (18, 'Економіка програмного забезпечення', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (19, 'Менеджмент проектів програмного забезпечення', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (20, 'Менеджмент проектів програмного забезпечення', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (21, 'Технології веб-програмування', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (22, 'Технології веб-програмування', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (23, 'Архітектура та проектування програмного забезпечення', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (24, 'Архітектура та проектування програмного забезпечення', 2);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (25, 'Методи об''єктно-орієнтованого проектування програмних систем', 1);
INSERT INTO public."Subjects" ("SubjectId", "Title", "SubjectTypeId") VALUES (26, 'Методи об''єктно-орієнтованого проектування програмних систем', 2);